### ISSUE TITLE
Incompatibility with First aid

### ISSUE THREAD

**Issue by SelfCombusted** [tarinoita/Spice-of-Life-Sweet-Potato#12]
**Description**
On a server, if a user attempts to leave the game, their playerdata will fail to be saved. 

**To Reproduce**
Install forge server with mods Spice of Life  and First Aid
Join server with same modlist as server
disconnect

Server fails to save player data

**Mod version and Forge version**
[solsweetpotato-1.18.2-2.0.0.jar]
forge-1.18.2-40.1.80
[FirstAid 1.11.1]

**Comment by SelfCombusted** [comment]
By the, way, i've tested this out on a modless forge server, a forge server with only first aid, a forge server with only SOL, and a forge server with a full modlist, and a forge server with only the two. Whenever the two are in the modlist, the issue triggers.

**Comment by tarinoita** [comment]
Hey! Thanks for testing different configurations & identifying the specific issue before reporting the bug. If you could include the crash log next time, I'll be able to get back to you a lot quicker, because it means I don't have to download these mods and reproduce the error myself.

After repro-ing, it seems like the problem is in the First Aid mod, or possibly their dependency Player Revive. The error I'm getting is [here](https://github.com/ichttt/FirstAid/blob/c6df2c124677d82b68b0d141319e0ffe6d94c8c6/src/main/java/ichttt/mods/firstaid/common/util/CommonUtils.java#L145) ("[player] is missing a damage model"), and the stacktrace seems to indicate PlayerMixin from the Player Revive mod is also involved, though it may have nothing to do with the core problem.

Both my mod and First Aid add functionality via Capabilities attached to the player, so they're probably conflicting somehow, but I can't tell exactly how. Since this also repros with version 1.0.2 of my mod, it's not due to the new code I added to properly handle capabilities on death or logout, which was the only hunch I had. I would raise the issue with them, and if they say I should be doing something different, feel free to come back and re-open this issue with whatever information they provide.
